name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened,synchronize]

jobs:
  simple_deployment_pipline:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install dependancies
        run: npm install
      - name: Build
        run: npm run build 

